baseURL: https://apisix.incubator.apache.org/
title: Apache APISIX
theme: hugo-fresh
googleAnalytics: #Put in your tracking code without quotes like this: UA-XXXXXX...
#Disables warningss
disableKinds:
 -taxonomy
 -taxonomyTerm

DefaultContentLanguage: en
languages:
  en:
    params:
      hero:
        # Main hero title
        title: Apache APISIX
        # Hero subtitle (optional)
        subtitle1: Cloud-native microservices API gateway, delivering the ultimate performance, security, open source and scalable platform for all your APIs and microservices.
        subtitle2: APISIX is based on Nginx and etcd. Compared with traditional API gateways, APISIX has dynamic routing and plug-in hot loading, which is especially suitable for API management under micro-service system.
        # Button text
        buttontext: View on GitHub
        # Where the main hero button links to
        buttonlink: "https://github.com/apache/incubator-apisix"
        downloadsButtonText: Downloads
        downloadsButtonLink: "./downloads"
        # Hero image (from static/images/___)
        image: illustrations/worker.svg
        # Footer logos (from static/images/logos/clients/___.svg)
        clientlogos:
        - systek
        - tribe
        - kromo
        - infinite
        - gutwork
      # Customizable navbar. For a dropdown, add a "sublinks" list.
      navbar:
      - title: Home
        url: /
      - title: Downloads
        url: /downloads
      - title: Get Involved
        sublinks:
        - title: Release Guide
          url: contribute/release
      language:
        name: 中
        link: /zh
      section1:
        title: Why Apache APISIX？
        tiles:
        - title: High availability, safety first
          icon: mouse-globe
          text: Built-in high-availability solution and multiple security plug-ins for identity authentication and interface verification, putting stability and security first.
        - title: Built-in Dashboard, powerful development interface
          icon: laptop-cloud
          text: It comes with a simple, easy-to-use built-in Dashboard and a powerful and flexible interface for developers to use.
        - title: Ultimate performance
          icon: plug-cloud
          text: From routing, json schema, to built-in plug-ins, which are designed and implemented to ultimate performance requirements.
        - title: Multi-protocol and multi-platform support
          icon: doc-sync
          text: Supports http to gRPC transcoding, supports websocket, gRPC, Dubbo, MQTT proxy, and supports multiple platforms including ARM64.
      section3:
        title: Who Uses Apache APISIX？
        image: https://raw.githubusercontent.com/iresty/iresty.com/master/user-wall.jpg
      section5: true
      footer:
        quicklinks:
          column1:
            title: "Disclaimer"
            text: Apache APISIX (incubating) is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by Incubator. Incubation is required of all newly accepted projects until a further review indicates that the infrastructure, communications, and decision making process have stabilized in a manner consistent with other successful ASF projects. While incubation status is not necessarily a reflection of the completeness or stability of the code, it does indicate that the project has yet to be fully endorsed by the ASF.
          column2:
            title: "Documentation"
            links:
            - text: Overview
              link: https://github.com/apache/incubator-apisix#apisix
            - text: Quick start
              link: https://github.com/apache/incubator-apisix#quickstart
            - text: Developer guide
              link: https://github.com/apache/incubator-apisix/blob/master/doc/architecture-design.md
          column3:
            title: "ASF"
            links:
            - text: Foundation
              link: http://www.apache.org/
            - text: License
              link: http://www.apache.org/licenses/
            - text: Events
              link: https://apachecon.com/?ref=apisix.incubator.apache.org
            - text: Sponsorship
              link: http://www.apache.org/foundation/sponsorship.html
            - text: Thanks
              link: http://www.apache.org/foundation/thanks.html
  zh:
    params:
    hero:
      # Main hero title
      title: Apache APISIX
      # Hero subtitle (optional)
      subtitle1: 云原生、高性能、可扩展的微服务 API 网关
      subtitle2: 基于 Nginx 和 etcd 来实现，具备动态路由、插件热加载和 gRPC 代理和协议转换功能，更适合微服务体系下的 API 管理
      # Button text
      buttontext: 访问 GitHub
      # Where the main hero button links to
      buttonlink: "https://github.com/apache/incubator-apisix"
      downloadsbuttontext: 下载
      downloadsbuttonlink: "../downloads"
      # Hero image (from static/images/___)
      image: illustrations/worker.svg
      # Footer logos (from static/images/logos/clients/___.svg)
      clientlogos:
      - systek
      - tribe
      - kromo
      - infinite
      - gutwork
    # Customizable navbar. For a dropdown, add a "sublinks" list.
    navbar:
    - title: 首页
      url: /
    - title: 下载
      url: /downloads
    - title: 参与
      sublinks:
      - title: 发布指南
        url: contribute/release
    language:
        name: EN
        link: /
    section1:
      title: 为什么选择 Apache APISIX？
      tiles:
      - title: 高可用，安全第一
        icon: mouse-globe
        text: 内置高可用方案，并提供多种身份认证和接口校验的安全插件，把稳定和安全放在第一位
      - title: 易用的管理界面，强大的开发接口
        icon: laptop-cloud
        text: 自带简洁、易用的管理界面，并提供强大、灵活的接口以便开发者使用
      - title: 极致性能
        icon: plug-cloud
        text: 从路由、json schema 检验，到内置的丰富插件，都是按照最高的性能要求来设计和实现
      - title: 多协议和多平台支持
        icon: doc-sync
        text: 支持 http 到 gRPC 的协议转换，支持 websocket、gRPC、Dubbo、MQTT 的代理，支持包括 ARM64 在内的多种平台
    section3:
      title: 谁在使用 Apache APISIX？
      image: https://raw.githubusercontent.com/iresty/iresty.com/master/user-wall.jpg
    section5: true
    footer:
      quicklinks:
        column1:
          title: "Disclaimer"
          text: Apache APISIX (incubating) is an effort undergoing incubation at The Apache Software Foundation (ASF), sponsored by Incubator. Incubation is required of all newly accepted projects until a further review indicates that the infrastructure, communications, and decision making process have stabilized in a manner consistent with other successful ASF projects. While incubation status is not necessarily a reflection of the completeness or stability of the code, it does indicate that the project has yet to be fully endorsed by the ASF.
        column2:
          title: "Documentation"
          links:
          - text: Overview
            link: https://github.com/apache/incubator-apisix#apisix
          - text: Quick start
            link: https://github.com/apache/incubator-apisix#quickstart
          - text: Developer guide
            link: https://github.com/apache/incubator-apisix/blob/master/doc/architecture-design.md
        column3:
          title: "ASF"
          links:
          - text: Foundation
            link: http://www.apache.org/
          - text: License
            link: http://www.apache.org/licenses/
          - text: Events
            link: https://apachecon.com/?ref=apisix.incubator.apache.org
          - text: Sponsorship
            link: http://www.apache.org/foundation/sponsorship.html
          - text: Thanks
            link: http://www.apache.org/foundation/thanks.html

params:
 # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
   image: logos/apisix.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
